name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  publish:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
          submodules: recursive

      - name: Dependencies
        run: |
          sudo apt install ruby-ffi ruby-sqlite3

      - name: Make Schemes
        run: |
          ./build_libvarnam.sh
          ./build_all_schemes.sh

      - name: Make Language Zips
        run: |
          ./build_all_languages.sh

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: all-languages
          path: "*.zip"
